// dom-framework-benchmark-checkpoint/apps/svelte/src/App.svelte
<script>
  import "../../../shared/styles.css";
  import {
    afterPaint,
    createTasks,
    mutateFirstTasks,
    priorities,
    readMemoryMB,
    removeFirstTasks
  } from "../../../shared/tasks.js";

  let tasks = [];
  let name = "";
  let priority = "Medium";
  let metrics = {
    render: "-",
    update: "-",
    deletion: "-",
    memory: readMemoryMB()
  };

  async function measure(label, operation) {
    const start = performance.now();
    operation();
    await afterPaint();
    metrics = {
      ...metrics,
      [label]: Number((performance.now() - start).toFixed(2)),
      memory: readMemoryMB()
    };
  }

  function addTask() {
    const trimmedName = name.trim();

    if (!trimmedName) {
      return;
    }

    tasks = [
      ...tasks,
      {
        id: Date.now(),
        name: trimmedName,
        priority
      }
    ];
    name = "";
  }

  function editTask(id, patch) {
    tasks = tasks.map((task) => (task.id === id ? { ...task, ...patch } : task));
  }

  function removeTask(id) {
    tasks = tasks.filter((task) => task.id !== id);
  }

  function renderTasks(count) {
    return measure("render", () => {
      tasks = createTasks(count);
    });
  }

  function updateFifty() {
    return measure("update", () => {
      tasks = mutateFirstTasks(tasks, 50);
    });
  }

  function deleteFifty() {
    return measure("deletion", () => {
      tasks = removeFirstTasks(tasks, 50);
    });
  }
</script>

<main class="app-shell">
  <section class="workspace">
    <header class="header">
      <div>
        <h1>Svelte DOM Benchmark</h1>
        <p>Todo list using Svelte keyed each blocks and compile-time DOM updates.</p>
      </div>
      <button class="secondary" on:click={() => (tasks = [])}>Clear</button>
    </header>

    <form class="panel controls" on:submit|preventDefault={addTask}>
      <label>
        Task name
        <input bind:value={name} placeholder="Add a task" />
      </label>
      <label>
        Priority
        <select bind:value={priority}>
          {#each priorities as item}
            <option>{item}</option>
          {/each}
        </select>
      </label>
      <button>Add task</button>
    </form>

    <section class="panel bench-controls">
      {#each [100, 500, 1000] as count}
        <button class="secondary" on:click={() => renderTasks(count)}>Render {count}</button>
      {/each}
      <button class="secondary" on:click={updateFifty} disabled={tasks.length < 50}>Update 50</button>
      <button class="danger" on:click={deleteFifty} disabled={tasks.length < 50}>Delete 50</button>
    </section>

    <section class="panel metrics">
      <div class="metric"><span>Tasks</span><strong>{tasks.length}</strong></div>
      <div class="metric"><span>Render ms</span><strong>{metrics.render}</strong></div>
      <div class="metric"><span>Update ms</span><strong>{metrics.update}</strong></div>
      <div class="metric"><span>Delete ms</span><strong>{metrics.deletion}</strong></div>
    </section>

    <section class="panel">
      <div class="task-list">
        {#if tasks.length === 0}
          <p class="empty">No tasks yet.</p>
        {/if}
        {#each tasks as task (task.id)}
          <article class="task-row">
            <input value={task.name} on:input={(event) => editTask(task.id, { name: event.currentTarget.value })} />
            <select value={task.priority} on:change={(event) => editTask(task.id, { priority: event.currentTarget.value })}>
              {#each priorities as item}
                <option>{item}</option>
              {/each}
            </select>
            <button class="danger" on:click={() => removeTask(task.id)}>Remove</button>
          </article>
        {/each}
      </div>
    </section>
  </section>
</main>

// dom-framework-benchmark-checkpoint/apps/angular/src/app/app.component.ts
import { CommonModule } from "@angular/common";
import { Component } from "@angular/core";
import { FormsModule } from "@angular/forms";

type Task = {
  id: number;
  name: string;
  priority: string;
};

type MetricValue = number | string;

const priorities = ["Low", "Medium", "High", "Critical"];

function createTasks(count: number): Task[] {
  return Array.from({ length: count }, (_, index) => ({
    id: index + 1,
    name: `Task ${index + 1}`,
    priority: priorities[(index + 1) % priorities.length]
  }));
}

function mutateFirstTasks(tasks: Task[], count = 50): Task[] {
  return tasks.map((task, index) => {
    if (index >= count) {
      return task;
    }

    return {
      ...task,
      name: `${task.name} - updated`,
      priority: priorities[(priorities.indexOf(task.priority) + 1) % priorities.length]
    };
  });
}

function removeFirstTasks(tasks: Task[], count = 50): Task[] {
  return tasks.slice(count);
}

function readMemoryMB(): number | string {
  const memory = (performance as Performance & { memory?: { usedJSHeapSize: number } }).memory;
  return memory?.usedJSHeapSize ? Number((memory.usedJSHeapSize / 1024 / 1024).toFixed(2)) : "N/A";
}

function afterPaint(): Promise<void> {
  return new Promise((resolve) => {
    requestAnimationFrame(() => requestAnimationFrame(() => resolve()));
  });
}

@Component({
  selector: "app-root",
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: "./app.component.html"
})
export class AppComponent {
  tasks: Task[] = [];
  name = "";
  priority = "Medium";
  priorities = priorities;
  metrics = {
    render: "-" as MetricValue,
    update: "-" as MetricValue,
    deletion: "-" as MetricValue,
    memory: readMemoryMB()
  };

  async measure(label: "render" | "update" | "deletion", operation: () => void): Promise<void> {
    const start = performance.now();
    operation();
    await afterPaint();
    this.metrics = {
      ...this.metrics,
      [label]: Number((performance.now() - start).toFixed(2)),
      memory: readMemoryMB()
    };
  }

  addTask(): void {
    const trimmedName = this.name.trim();

    if (!trimmedName) {
      return;
    }

    this.tasks = [
      ...this.tasks,
      {
        id: Date.now(),
        name: trimmedName,
        priority: this.priority
      }
    ];
    this.name = "";
  }

  renderTasks(count: number): Promise<void> {
    return this.measure("render", () => {
      this.tasks = createTasks(count);
    });
  }

  updateFifty(): Promise<void> {
    return this.measure("update", () => {
      this.tasks = mutateFirstTasks(this.tasks, 50);
    });
  }

  deleteFifty(): Promise<void> {
    return this.measure("deletion", () => {
      this.tasks = removeFirstTasks(this.tasks, 50);
    });
  }

  removeTask(id: number): void {
    this.tasks = this.tasks.filter((task) => task.id !== id);
  }

  trackTask(_index: number, task: Task): number {
    return task.id;
  }
}

<main class="app-shell">
  <section class="workspace">
    <header class="header">
      <div>
        <h1>Angular DOM Benchmark</h1>
        <p>Todo list using Angular standalone components, ngFor, ngIf, ngModel, and trackBy.</p>
      </div>
      <button class="secondary" type="button" (click)="tasks = []">Clear</button>
    </header>

    <form class="panel controls" (ngSubmit)="addTask()">
      <label>
        Task name
        <input name="taskName" [(ngModel)]="name" placeholder="Add a task" />
      </label>
      <label>
        Priority
        <select name="priority" [(ngModel)]="priority">
          <option *ngFor="let item of priorities" [value]="item">{{ item }}</option>
        </select>
      </label>
      <button type="submit">Add task</button>
    </form>

    <section class="panel bench-controls">
      <button class="secondary" type="button" (click)="renderTasks(100)">Render 100</button>
      <button class="secondary" type="button" (click)="renderTasks(500)">Render 500</button>
      <button class="secondary" type="button" (click)="renderTasks(1000)">Render 1000</button>
      <button class="secondary" type="button" (click)="updateFifty()" [disabled]="tasks.length < 50">Update 50</button>
      <button class="danger" type="button" (click)="deleteFifty()" [disabled]="tasks.length < 50">Delete 50</button>
    </section>

    <section class="panel metrics">
      <div class="metric"><span>Tasks</span><strong>{{ tasks.length }}</strong></div>
      <div class="metric"><span>Render ms</span><strong>{{ metrics.render }}</strong></div>
      <div class="metric"><span>Update ms</span><strong>{{ metrics.update }}</strong></div>
      <div class="metric"><span>Delete ms</span><strong>{{ metrics.deletion }}</strong></div>
    </section>

    <section class="panel">
      <div class="task-list">
        <p *ngIf="tasks.length === 0" class="empty">No tasks yet.</p>
        <article *ngFor="let task of tasks; trackBy: trackTask" class="task-row">
          <input [(ngModel)]="task.name" [name]="'task-' + task.id" />
          <select [(ngModel)]="task.priority" [name]="'priority-' + task.id">
            <option *ngFor="let item of priorities" [value]="item">{{ item }}</option>
          </select>
          <button class="danger" type="button" (click)="removeTask(task.id)">Remove</button>
        </article>
      </div>
    </section>
  </section>
</main>
